[package]
name = "mt940"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]

[dependencies]
clap = "2"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "0.10", features = ["serde"] }
log = "0.4"
pest = "2"
pest_derive = "2"
serde = "1"
serde_derive = "1"
serde_json = "1"
strum = "0.11"
strum_macros = "0.11"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
pretty_assertions = "0.5"
rstest = "0.2"
skeptic = "0.13"
proptest = "0.8.7"
regex = "1"
