[package]
name = "mt940-rs"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2"
pest_derive = "2"

[dev-dependencies]
pretty_assertions = "0.5"
